[package]
name = "dev"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]


[dependencies]
egg = "0.9.5"
serde = { version = "1.0.203", features = ["derive"] }
serde-pickle = "1.1.1"
serde_json = "1.0.118"
