[package]
name = "dev"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
egg = { version = "0.9.5" }
lazy_static = "1.5.0"
num = "0.4.3"
num_enum = "0.7.2"
serde = { version = "1.0.203", features = ["derive"] }
serde-pickle = "1.1.1"
